
# Generated by Django 3.2.9 on 2023-03-23 11:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_establish', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('committee_date', models.DateTimeField()),
                ('type', models.TextField(choices=[('APPOINTMENTS_COMMITTEE', 'Committee 0'), ('PROFESSIONAL_COMMITTEE', 'Committee 1')], default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('institute', models.TextField(max_length=50)),
                ('field_of_study', models.TextField(max_length=50)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_rank', to='core.rank')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='employment_stage',
            field=models.TextField(choices=[('A', 'Stage 0'), ('B', 'Stage 1'), ('C', 'Stage 2')], default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_due_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=None, upload_to='images/'),
        ),

        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(choices=[('APPROVAL_RECOMMENDED_BY_A_PROFESSIONAL_COMMITTEE', 'State 0'), ('NOT_YET_APPROVED_BY_A_PROFESSIONAL_COMMITTEE', 'State 1'), ('APPROVED', 'State 2'), ('REJECTED', 'State 3')], max_length=50)),
                ('recommendation_letter', models.FileField(upload_to='')),
                ('familiarity_level', models.TextField(choices=[('PROFESSIONAL', 'Level 0'), ('PERSONAL', 'Level 1')], max_length=20)),
                ('recommend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_id', to='core.recommend')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rl_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.TextField(choices=[('', 'Document 0')], default=None, max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('note', models.TextField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dl_user_id', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chairman', models.BooleanField(default=False)),
                ('committee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_id', to='core.committee')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_user_id', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type_id', models.TextField(choices=[('THE_CHAIRMAN_OF_APPOINTMENTS_APPROVED_THE_OPENING_OF_A_PROCESS', 'Alert 0 Admin'), ('THE_CHAIRMAN_OF_APPOINTMENTS_REJECTED_THE_OPENING_OF_A_PROCESS', 'Alert 1 Admin'), ('ATTACHED_TEACHING_FEEDBACK', 'Alert 2 Admin'), ('CANDIDATE_ATTACHED_REQUIRED_MATERIAL', 'Alert 3 Admin'), ('CANDIDATES_FOR_A_PROFESSIONAL_COMMITTEE_HAVE_BEEN ADDED', 'Alert 4 Admin')], default=None, max_length=65)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_user_id', to='core.profile')),
            ],
        ),
    ]
