# Generated by Django 3.2.9 on 2023-04-01 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20230328_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='statusAlert',
            field=models.TextField(choices=[('new requests', 'Statues 0'), ('opening a process', 'Statues 1'), ('establishment of a professional committee', 'Statues 2'), ('professional committee', 'Statues 3'), ('final appointments committee', 'Statues 4'), ('requests for the CHE', 'Statues 5')], default=None, max_length=65),
        ),
        migrations.AlterField(
            model_name='alert',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
