# Generated by Django 4.2 on 2023-05-01 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_remove_application_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='note',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='Files/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
