# Generated by Django 4.2 on 2023-05-19 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_remove_application_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='last_name',
        ),
        migrations.AddField(
            model_name='recommend',
            name='name',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommend_id',
            field=models.ForeignKey(default='NOT_YET_APPROVED_BY_A_PROFESSIONAL_COMMITTEE',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='recommend_id',
                                    to='core.recommend'),
        ),
    ]
