# Generated by Django 4.2 on 2023-05-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_remove_application_department_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='recommend',
            name='country',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
