# Generated by Django 4.2 on 2023-05-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_remove_application_department_recommend_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommend_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_id',
                                    to='core.recommend'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_letter',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='state',
            field=models.TextField(choices=[('APPROVAL_RECOMMENDED_BY_A_PROFESSIONAL_COMMITTEE', 'State 0'),
                                            ('NOT_YET_APPROVED_BY_A_PROFESSIONAL_COMMITTEE', 'State 1'),
                                            ('APPROVED', 'State 2'), ('REJECTED', 'State 3')],
                                   default='NOT_YET_APPROVED_BY_A_PROFESSIONAL_COMMITTEE', max_length=50),
        ),
    ]
