# Generated by Django 4.2 on 2023-05-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_application_department_alter_profile_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeecandidate',
            name='user_id',
        ),
        migrations.AddField(
            model_name='committeecandidate',
            name='degree',
            field=models.TextField(choices=[("פרופ'", 'Prof'), ('מר.', 'Mr'), ("גב'", 'Mis'), ('ד"ר', 'Doc')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='committeecandidate',
            name='email',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='committeecandidate',
            name='full_name',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='committeecandidate',
            name='institution',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='committeecandidate',
            name='phone',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='committeecandidate',
            name='research_area',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='committee_ID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee_ID', to='core.committee'),
        ),
        migrations.AlterField(
            model_name='applicationstep',
            name='step_name',
            field=models.TextField(choices=[('NEW-REQUESTS/APPROVE-ADMIN', 'Step 0'), ('NEW-REQUESTS/APPROVE-CHAIRMAN-APPOINTMENTS', 'Step 1'), ('NEW-REQUESTS/COMBINATION-TEACHING-FEEDBACK', 'Step 2'), ('OPEN-PROCESS/APPOINTMENT-COMMITTEE-DETERMINATION', 'Step 3'), ('OPEN-PROCESS/APPOINTMENT-COMMITTEE-WAITING', 'Step 4'), ('OPEN-PROCESS/ENTER-APPOINTMENT-COMMITTEE-DECISION', 'Step 5'), ('ESTABLISHMENT-PROFESSIONAL-COMMITTEE/RECEIVING-MATERIAL-CANDIDATE', 'Step 6'), ('ESTABLISHMENT-PROFESSIONAL-COMMITTEE/LOCATING-CHAIRMAN-APPOINTMENTS-COMMITTEE', 'Step 7'), ('ESTABLISHMENT-PROFESSIONAL-COMMITTEE/ADDITION-MEMBERS-PROFESSIONAL-COMMITTEE', 'Step 8'), ('ESTABLISHMENT-PROFESSIONAL-COMMITTEE/SETTING-DATE-APPOINTMENTS-COMMITTEE', 'Step 9'), ('ESTABLISHMENT-PROFESSIONAL-COMMITTEE/APPOINTMENT-COMMITTEE-WAITING', 'Step 10'), ('ESTABLISHMENT-PROFESSIONAL-COMMITTEE/ATTACHMENT-PROTOCOL-AND-LETTERS-APPOINTMENT', 'Step 11'), ('PROFESSIONAL-COMMITTEE/CONTACT-RECOMMENDERS -AND-ATTACHING-LETTERS-RECOMMENDATION', 'Step 12'), ('PROFESSIONAL-COMMITTEE/DETERMINE-PROFESSIONAL-COMMITTEE-REPORT-RECOMMENDATIONS', 'Step 13'), ('FINAL-APPOINTMENTS-COMMITTEE/DETERMINATION-FINAL-COMMITTEE', 'Step 14'), ('FINAL-APPOINTMENTS-COMMITTEE/APPOINTMENT-COMMITTEE-WAITING', 'Step 15'), ('FINAL-APPOINTMENTS-COMMITTEE/ENTER-COMMITTEE-DECISION', 'Step 16'), ('REQUEST-CHE/COMPLETING-DOCUMENTS', 'Step 17'), ('REQUEST-CHE/ENTER-GENERAL-ASSEMBLY-DECISION', 'Step 18'), ('FINISH', 'Step 19')], max_length=100),
        ),
    ]
