# Generated by Django 4.2 on 2023-05-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_remove_application_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommendation_letter',
        ),
    ]
