# Generated by Django 4.2 on 2023-05-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_remove_application_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='committee_ID',
        ),
        migrations.AddField(
            model_name='application',
            name='committee_ID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='committee_ID', to='core.committee'),
        ),
    ]
